### ISSUE TITLE
[JS] ajv schema validator is not configured with formats

### ISSUE THREAD

**Issue by pavelgj** [firebase/genkit#206] opened 2024-05-21 16:40 UTC
**Describe the bug**
Context: https://stackoverflow.com/questions/78496888/how-do-i-specify-a-date-property-using-zod-in-firebase-genkit

schema validator is missing configuration for formats: https://ajv.js.org/packages/ajv-formats.html

So any time a format is included in the schema (ex. date time) ajv throws an error:

```
name: 'Error', message: 'unknown format "date" ignored in schema at path "#/properties/date"',
```

**To Reproduce**

Use this schema anywhere in the path of schema validator

```js
export const SearchCriteria = z.object({
  zip: z.string(),
  date: z.string().datetime({ offset: false }),
  timeOfDay: z.enum(["morning", "afternoon", "evening"]).optional(),
});
```

**Comment by maxl0rd** [comment] 2024-05-21 16:50
What are you thinking here? Should we export a function to extend the internal ajv instance with user-supplied formats, just install the kitchen sink by default, both?

**Comment by pavelgj** [comment] 2024-05-21 16:54
> What are you thinking here? Should we export a function to extend the internal ajv instance with user-supplied formats, just install the kitchen sink by default, both?

My first reaction was that we should probably just install common ajv formats... but supporting use-supplied formats (or even a custom validator) is something to consider (in the future) maybe?

**Comment by maxl0rd** [comment] 2024-05-23 17:00
Duplicate of https://github.com/firebase/genkit/issues/227 which has a fix attached.

**Closed by maxl0rd** 2024-05-23 17:00 UTC
Labels: bug, js
