### ISSUE TITLE
[JS] Confusing Error Message When `apiKey` is Not Passed in Configuration

### ISSUE THREAD

**Issue by ManiDoraisamy** [firebase/genkit#328] opened 2024-06-05 19:45 UTC
**Describe the bug**
When the `apiKey` is not passed in the configuration for the `generate` function, the error message is confusing and suggests that the model is not found, instead of indicating that the `apiKey` is missing.

**To Reproduce**
1. Set up a project using Genkit.
2. Do not include the `apiKey` in the `generate` function's configuration.
3. Run the code.

**Expected behavior**
A clear error message indicating that the `apiKey` is missing and should be included in the configuration.

**Code Snippet**
```javascript
const { generate } = require('@genkit-ai/ai');
const { geminiPro } = require('@genkit-ai/googleai');

exports.generate = function() {
    console.log('generate for', geminiPro);
    return generate({
        model: geminiPro,
        config: { 
            temperature: 0.3, 
            maxOutputTokens: 200
            // apiKey is missing here
        },
        prompt: 'What makes you the best LLM out there?',
    })
    .then(result => {
        return result.text();
    })
    .catch(error => {
        console.error('Error generating response:', error);
        throw error;
    });
}
```

**Error Message**
```
Error: Model {"name":"googleai/gemini-pro","info":{"label":"Google AI - Gemini Pro","versions":["gemini-1.0-pro","gemini-1.0-pro-latest","gemini-1.0-pro-001"],"supports":{"multiturn":true,"media":false,"tools":true,"systemRole":true}},"configSchema":{"_def":{"unknownKeys":"strip","catchall":{"_def":{"typeName":"ZodNever"}},"typeName":"ZodObject"},"_cached":null}} not found
    at C:\work\Promptrepo\functions\node_modules\@genkit-ai\ai\lib\generate.js:513:13
    at Generator.next (<anonymous>)
    at fulfilled (C:\work\Promptrepo\functions\node_modules\@genkit-ai\ai\lib\generate.js:53:24)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

**Additional context**
The error message should more accurately reflect the issue with the missing `apiKey`. It would help if the error message guided the user to include the `apiKey` in the configuration using `configureGenkit`.

**Environment:**
- OS: [e.g., Windows 10]
- Node.js version: [e.g., 14.17.0]
- Genkit version: [e.g., 1.0.0-beta]

**Comment by ManiDoraisamy** [comment] 2024-06-06 17:46
You are right, @MichaelDoyle! I didnt call configureGenkit() and therefore googleAI plugin was not loaded. But, this error message looks like the Model not found :
```
>  Error: Model {"name":"googleai/gemini-pro","info":{"label":"Google AI - Gemini Pro","versions":["gemini-1.0-pro","gemini-1.0-pro-latest","gemini-1.0-pro-001"],"supports":{"multiturn":true,"media":false,"tools":true,"systemRole":true}},"configSchema":{"_def":{"unknownKeys":"strip","catchall":{"_def":{"typeName":"ZodNever"}},"typeName":"ZodObject"},"_cached":null}} not found
>      at C:\work\Promptrepo\functions\node_modules\@genkit-ai\ai\lib\generate.js:513:13
>      at Generator.next (<anonymous>)
>      at fulfilled (C:\work\Promptrepo\functions\node_modules\@genkit-ai\ai\lib\generate.js:53:24)
>      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

May be, the error message could be "Plugin for googleai/gemini-pro not initialized. Initialized it with configureGenkit()"?

**Comment by ManiDoraisamy** [comment] 2024-06-06 17:52
Just noticed, this is already filed here: https://github.com/firebase/genkit/issues/173
Please close this as duplicate.

**Comment by MichaelDoyle** [comment] 2024-06-06 19:10
Thanks again for your report - it really does help us continue to iterate and improve. We'll definitely make this experience better.

**Comment by MichaelDoyle** [comment] 2024-06-06 19:11
Duplicate of #173

**Closed by MichaelDoyle** 2024-06-06 19:11 UTC
Labels: bug, js
