### ISSUE TITLE
[Tooling] Poll for action listing instead of erroring

### ISSUE THREAD

**Issue by mbleigh** [firebase/genkit#903] opened 2024-09-14 03:41 UTC
Sometimes there are funky race conditions or reasons that the Genkit UI gets accessed by a developer before the reflection API is up and running properly and connected (we received reports of this happening in IDX).

I recommend that if we receive an error while trying to call the reflection API rather than print an ugly error message and that's it, we display a message like "Unable to connect to Genkit development server, trying again in XXs" and then it has a backoff (maybe 1s, 2s, 5s, 10s, then fail completely).

Or if not an automatic retry, for a quick and dirty solution perhaps just a message like "Unable to connect to Genkit development server. Please refresh to try loading again." where refresh is a link to `window.location.reload()`.

**Comment by pavelgj** [comment] 2024-09-16 11:29
Duplicate of https://github.com/firebase/genkit/issues/709

**Closed by pavelgj** 2024-09-16 11:29 UTC
Labels: bug, tooling
