### ISSUE TITLE
[Vertex] Support multimodal embeddings

### ISSUE THREAD

**Issue by mbleigh** [firebase/genkit#1463] opened 2024-12-06 18:45 UTC
Vertex plugin should support [multimodal embeddings](https://cloud.google.com/vertex-ai/generative-ai/docs/embeddings/get-multimodal-embeddings).

**Comment by pavelgj** [comment] 2024-12-07 00:00
Duplicate of https://github.com/firebase/genkit/issues/1078
@ifielker already working on it.

**Closed by pavelgj** 2024-12-07 00:00 UTC
